### ISSUE TITLE
Cleanup Playwright Test Logs

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#1638]
## Description

The Playwright logs are very noisy and bloated with a bunch of information which makes it difficult to decipher what actually failed.

![image](https://user-images.githubusercontent.com/22064420/236012260-ea8a9ca6-bb0b-4c3f-a1a8-54e90a26dbf4.png)

### To Do:

- There are multiple issues that cause the logs to be bloated, one of those issues has to do with the `custom` Nextjs servers we created in order to enable dynamic mocks #1238. When addressing #1238, it appeared that we could not configure the `custom` Nextjs server to log to a file instead of `stdout/stderr`. We should investigate if this still holds true, otherwise, we should look into having a single `custom` Nextjs server to reduce the noise.

- Another issue is:
```
FetchError: request to https://www.cominor.com/api/2.0/store/product/iphone-6s-plus-replacement-battery-out-of-stock failed, reason: socket hang up
    at NodeClientRequest.<anonymous> (/home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/next@12.2.3_t7ss3ubh4wigfvyfclbvqff3gm/node_modules/next/dist/compiled/node-fetch/index.js:1:65763)
    at NodeClientRequest.emit (node:events:513:28)
    at NodeClientRequest.emit (node:domain:489:12)
    at NodeClientRequest.emit (/home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@mswjs+interceptors@0.17.6/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:299:22)
    at /home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@mswjs+interceptors@0.17.6/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:190:14
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
} {
  _resource: 'https://www.cominor.com/api/2.0/store/product/iphone-6s-plus-replacement-battery-out-of-stock',
  headers: undefined,
  method: 'GET',
  body: undefined
}
```

- Unauthorized Requests
```
[WebServer] Error: Unauthorized
    at IFixitAPIClient.fetch (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/chunks/838.js:1467:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fetchMultipleDeviceImages (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/chunks/585.js:158:24)
    at async fetchMissingImages (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/chunks/585.js:323:25)
    at async Promise.all (index 0)
    at async getProductListChildren (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/chunks/585.js:287:50)
    at async findProductList (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/chunks/585.js:251:19)
    at async Proxy.get (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/chunks/385.js:490:23)
    at async /home/runner/work/react-commerce/react-commerce/frontend/.next/server/chunks/463.js:5394:35
```

- Page Size Warning
```
[WebServer] Warning: data for page "/Parts" is 156 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
See more info here: https://nextjs.org/docs/messages/large-page-data
```

- useLayoutEffect Warning
```
[WebServer] Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at IFixitBreadcrumb (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/pages/Vulcan/[wikiname].js:1187:112)
    at div
    at /home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@emotion+react@11.10.5_5sk75k55old2mvxbb7qmm7otxe/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at ChakraComponent (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+system@2.4.0_dovxhg2tvkkxkdnqyoum6wzcxm/node_modules/@chakra-ui/system/dist/chunk-E32MZNBA.mjs:42:35)
    at Flex2 (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+layout@2.1.14_ublygk26yvqigtycgan52uuiea/node_modules/@chakra-ui/layout/dist/chunk-MPFPK3CX.mjs:8:11)
    at DynamicBreadCrumbs (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/pages/Vulcan/[wikiname].js:1137:109)
    at div
    at /home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@emotion+react@11.10.5_5sk75k55old2mvxbb7qmm7otxe/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at ChakraComponent (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+system@2.4.0_dovxhg2tvkkxkdnqyoum6wzcxm/node_modules/@chakra-ui/system/dist/chunk-E32MZNBA.mjs:42:35)
    at Flex2 (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+layout@2.1.14_ublygk26yvqigtycgan52uuiea/node_modules/@chakra-ui/layout/dist/chunk-MPFPK3CX.mjs:8:11)
    at div
    at /home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@emotion+react@11.10.5_5sk75k55old2mvxbb7qmm7otxe/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at ChakraComponent (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+system@2.4.0_dovxhg2tvkkxkdnqyoum6wzcxm/node_modules/@chakra-ui/system/dist/chunk-E32MZNBA.mjs:42:35)
    at Flex2 (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+layout@2.1.14_ublygk26yvqigtycgan52uuiea/node_modules/@chakra-ui/layout/dist/chunk-MPFPK3CX.mjs:8:11)
    at NavBar (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/pages/Vulcan/[wikiname].js:214:19)
    at div
    at /home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@emotion+react@11.10.5_5sk75k55old2mvxbb7qmm7otxe/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at ChakraComponent (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+system@2.4.0_dovxhg2tvkkxkdnqyoum6wzcxm/node_modules/@chakra-ui/system/dist/chunk-E32MZNBA.mjs:42:35)
    at Flex2 (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+layout@2.1.14_ublygk26yvqigtycgan52uuiea/node_modules/@chakra-ui/layout/dist/chunk-MPFPK3CX.mjs:8:11)
    at Wiki (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/pages/Vulcan/[wikiname].js:110:17)
    at div
    at /home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@emotion+react@11.10.5_5sk75k55old2mvxbb7qmm7otxe/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at ChakraComponent (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+system@2.4.0_dovxhg2tvkkxkdnqyoum6wzcxm/node_modules/@chakra-ui/system/dist/chunk-E32MZNBA.mjs:42:35)
    at Flex2 (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+layout@2.1.14_ublygk26yvqigtycgan52uuiea/node_modules/@chakra-ui/layout/dist/chunk-MPFPK3CX.mjs:8:11)
    at div
    at /home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@emotion+react@11.10.5_5sk75k55old2mvxbb7qmm7otxe/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at ChakraComponent (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+system@2.4.0_dovxhg2tvkkxkdnqyoum6wzcxm/node_modules/@chakra-ui/system/dist/chunk-E32MZNBA.mjs:42:35)
    at ShopifyStorefrontProvider (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/chunks/838.js:1547:38)
    at /home/runner/work/react-commerce/react-commerce/frontend/.next/server/chunks/838.js:1292:21
    at EnvironmentProvider (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+react-env@2.0.13_react@18.2.0/node_modules/@chakra-ui/react-env/dist/chunk-DNC4K5KS.mjs:29:11)
    at ColorModeProvider (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+color-mode@2.1.12_react@18.2.0/node_modules/@chakra-ui/color-mode/dist/chunk-4DEUOPYU.mjs:22:5)
    at ThemeProvider (/home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@emotion+react@11.10.5_5sk75k55old2mvxbb7qmm7otxe/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:106:21)
    at ThemeProvider (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+system@2.4.0_dovxhg2tvkkxkdnqyoum6wzcxm/node_modules/@chakra-ui/system/dist/chunk-3ZTTLJBV.mjs:13:11)
    at ChakraProvider (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+provider@2.0.30_5rzy53przelm5jchjmb5vr6dxy/node_modules/@chakra-ui/provider/dist/chunk-D2K5YHXV.mjs:15:5)
    at ChakraProvider2 (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@chakra-ui+react@2.4.8_dcg2t2i3u3zsy6dxglozcx6cvu/node_modules/@chakra-ui/react/dist/chunk-DGNA6VRZ.mjs:13:5)
    at QueryClientProvider (file:///home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/@tanstack+react-query@4.14.5_biqbaboplfbrettd7655fr4n2y/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:40:3)
    at CartDrawerProvider (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/chunks/838.js:2489:31)
    at AppProvider (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/chunks/838.js:348:24)
    at AppProviders (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/chunks/489.js:67:25)
    at ServerSidePropsProvider (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/pages/_app.js:165:36)
    at MyApp (/home/runner/work/react-commerce/react-commerce/frontend/.next/server/pages/_app.js:52:18)
    at StyleRegistry (/home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/styled-jsx@5.0.2_et5i55zp7clbjcgn5kgecqydai/node_modules/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/next@12.2.3_t7ss3ubh4wigfvyfclbvqff3gm/node_modules/next/dist/server/render.js:[404](https://github.com/iFixit/react-commerce/actions/runs/4862704069/jobs/8669428291#step:9:405):29)
    at AppContainerWithIsomorphicFiberStructure (/home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/next@12.2.3_t7ss3ubh4wigfvyfclbvqff3gm/node_modules/next/dist/server/render.js:433:57)
    at div
    at Body (/home/runner/work/react-commerce/react-commerce/node_modules/.pnpm/next@12.2.3_t7ss3ubh4wigfvyfclbvqff3gm/node_modules/next/dist/server/render.js:690:21)
```

**Comment by batbattur** [comment]
The test logs now look more readable: [example](https://github.com/iFixit/react-commerce/actions/runs/5123708642/jobs/9246252305).

<hr>

1. Fixed the `Unauthorized Requests` in https://github.com/iFixit/ifixit/pull/48182.

2. Most of the noisy test logs were already fixed on master, which include:
   - `FetchError: request to ... failed, reason: socket hang up`, probably fixed by https://github.com/iFixit/react-commerce/issues/1627
   - `useLayoutEffect Warning`: we don't see it anymore in the logs. If it shows up again, we can fix it using [this approach](https://medium.com/@alexandereardon/uselayouteffect-and-ssr-192986cdcf7a) (also it looked like we already use it [here](https://github.com/iFixit/react-commerce/blob/19dd5da80e4b9efc3daa6a7bc23b356bf981e4d3/packages/ui/hooks/index.ts#L64C1-L65)).

3. Decided to leave the `Page Size Warning` warning as-is in the test logs since it's only 2 lines and as it may require a significant amount of refactoring for how we pass the props. This warning shows up because the data passed through the props on `/Parts` page is larger than the threshold. The current page data size is about `146kB` (can be found by running `document.getElementById("__NEXT_DATA__").text` on the page), but the normal threshold is `128kB`, [ref](https://nextjs.org/docs/messages/large-page-data):
<img width="1560" alt="Screen Shot 2023-05-31 at 5 18 02 PM" src="https://github.com/iFixit/react-commerce/assets/58952979/21b0dde4-67b1-4ad9-8e6e-40e605ba3e10">

If we really want to fix this, we could do something like this to [modify the threshold for the next config for ci](https://github.com/iFixit/react-commerce/commit/249d86bf967097dd85cce7502d54f6bbc25897ea), however, this seems hacky and not a long-term solution. Here's how the logs looks with the modified threshold: [logs](https://github.com/iFixit/react-commerce/actions/runs/5138648171/jobs/9248379431#step:9:22). 

<hr>

Going to close this as completed. We can reopen this if more noisy logs pop up again.
