### ISSUE TITLE
Product List Downtime 2022-11-04

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#989]
- Sentry should catch this
- Strapi should have defaulted to false
    - Does new strapi fix this?
- Did GraphQL fail or did our nextjs app reject the result?
- Should we have been serving stale pages because of the error?
- This should have been a 500

**Comment by federicobadini** [comment]
### Repro steps

1. Cleaned the Strapi model from reference to the new boolean in order to generate a new Strapi instance without any reference to it
2. Added a new boolean **required** field with default `false`
3. Migrate the existing instance
4. Modify the frontend to query the newly created field

### Strapi response

If you follow the steps above and try to manually query the Strapi server, you'll receive the following response:

```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field ProductList.testBoolean.",
      "locations": [
        {
          "line": 13,
          "column": 9
        }
      ],
      "path": [
        "productLists",
        "data",
        0,
        "attributes",
        "testBoolean"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field ProductList.testBoolean.",
            "    at completeValue (/Users/federicobadini/Documents/Projects/react-commerce/backend/node_modules/graphql/execution/execute.js:559:13)",
            "    at /Users/federicobadini/Documents/Projects/react-commerce/backend/node_modules/graphql/execution/execute.js:469:16",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async Promise.all (index 7)",
            "    at async Promise.all (index 1)",
            "    at async Promise.all (index 0)",
            "    at async Promise.all (index 0)",
            "    at async Promise.all (index 0)",
            "    at async execute (/Users/federicobadini/Documents/Projects/react-commerce/backend/node_modules/apollo-server-koa/node_modules/apollo-server-core/dist/requestPipeline.js:205:20)",
            "    at async processGraphQLRequest (/Users/federicobadini/Documents/Projects/react-commerce/backend/node_modules/apollo-server-koa/node_modules/apollo-server-core/dist/requestPipeline.js:148:28)"
          ]
        }
      }
    }
  ],
  "data": {
    "productLists": {
      "data": [
        {
          "id": "2226",
          "attributes": null
        }
      ]
    }
  }
}
```

So Strapi is effectively raising an error since its model is not matching the existing data --> no default was set
Restarting Strapi produced no effect either.

### Error handling

This is effectively a 200 status code response so we are not catching this.
[Here](https://github.com/iFixit/react-commerce/blob/c5ca7c88b829f3d48d91eedcd6f3135d99e4d529/frontend/lib/strapi-sdk/index.ts#L27-L31) we are just checking the status code and the presence of data, but we have both. 
As a consequence the `findProductList` receives just `{"id": "2226", "attributes": null }` and finding `null` [here](https://github.com/iFixit/react-commerce/blob/c5ca7c88b829f3d48d91eedcd6f3135d99e4d529/frontend/models/product-list/index.ts#L61) returns a 404.

### Conclusions
Both Strapi and our app are not handling this fail safe.

We should make the [`requester`](https://github.com/iFixit/react-commerce/blob/c5ca7c88b829f3d48d91eedcd6f3135d99e4d529/frontend/lib/strapi-sdk/index.ts#L7) function more robust in order to handle all these model/data inconsistencies which will lead to 200 responses with errors as a part of the payload.

We should not set additional fields as required if records are already present at least until Strapi will not handle this applying the correct defaults to existing data

**Comment by derrickmehaffy** [comment]
Thanks for reporting this (from Strapi).

Ive got this on my list to take a look at shortly. I'll be flying up to San Francisco this weekend for Jamstack conf but if I get some time Mon/Tues I'll dig in else I'll run through your codebase on Wednesday and see what we can do from the Strapi side to fix the issue.

**Comment by federicobadini** [comment]
Still present on 4.4.7

Adding a new required field in the model create unset properties inside existing records.

<img width="1723" alt="Screenshot 2023-01-10 at 17 53 47" src="https://user-images.githubusercontent.com/7805759/211617066-329bff29-7891-4d7d-addd-c0a13aaedc40.png">

At query time however the constraint is enforced, leading to the same `Cannot return null for non-nullable field` error that was present on previous versions.
